spring:
    application:
        name: ambar-enquiry-service
    datasource:
        driverClassName: org.postgresql.Driver
        # URL for running within docker network
        url: jdbc:postgresql://postgres-enquiry:5432/postgres?currentSchema=enquiry
        # URL for running locally with dockerised postgres
        #url: jdbc:postgresql://localhost:5433/postgres?currentSchema=enquiry
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
            hibernate:
                default_schema: enquiry
        hibernate:
            ddl-auto: validate
        generate-ddl: false
    data:
        rest:
            detection-strategy: annotated
    flyway:
        schemas: enquiry
    jackson:
        deserialization:
            fail-on-unknown-properties: false

server:
    port: 8099
